#pragma once

#define CMD_CHOSEPROG 1
#define CMD_CREATERUL 2
#define CMD_CHECKPROGNAME 3
#define CMD_STARTTRACKING 4
#define CMD_STOPTRACKING 5
#define CMD_SAVETOFILE 6
#define CMD_LOADFROMFILE 7
#define CMD_DELETERULE 8